name: CD
run-name: CD - ${{ github.event.head_commit.message }}

on:
  push:
    tags: [v*]

defaults:
  run:
    working-directory: src

jobs:
  build_and_test:
    name: 🛠️ Build & 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: .config/global.json

      - name: build and test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=coverage/lcov.info --configuration Release

      - name: Coveralls UnitTests
        uses: coverallsapp/github-action@v2.2.0
        with:
          path-to-lcov: test/dotnet-test-rerun.UnitTests/coverage/lcov.info
          flag-name: UnitTests

      - name: Coveralls IntegrationTests
        uses: coverallsapp/github-action@v2.2.0
        with:
          path-to-lcov: test/dotnet-test-rerun.IntegrationTests/coverage/lcov.info
          flag-name: IntegrationTests

      - name: pack
        run: dotnet pack --configuration Release --no-build --no-restore

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-test-rerun-nupkg
          path: nupkg/*.nupkg
          retention-days: 1

  publish:
    name: 🚚 Push
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-test-rerun-nupkg

      - name: push
        run: dotnet nuget push nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY --skip-duplicate
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}